sonar.projectKey=utilForever_roguekit
sonar.organization=utilforever-github
sonar.host.url=https://sonarcloud.io

sonar.sources=src,bracket-algorithm-traits/src,bracket-color/src,bracket-geometry/src,bracket-noise/src,bracket-pathfinding/src,bracket-random/src,bracket-terminal/src,bracket-rex/src,bracket-embedding/src,bracket-bevy/src,rltk/src
sonar.exclusions=target/**
sonar.rust.lcov.reportPaths=coverage/lcov.info